pipeline {
    agent {
        docker {
            image "maven:3.9.6-eclipse-temurin-17"
            args "-v /root/.m2:/root/.m2"
        }
    }
    stages {
        stage("Build") {
            steps {
                sh "mvn clean compile"
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
        stage("Package") {
            steps {
                sh "mvn package"
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: "target/*.jar", fingerprint: true
        }
        always {
            cleanWs()
        }
    }
}
